### ISSUE TITLE
US 04.05.01(Add Picked Item to ingredient storage)

### ISSUE THREAD

**Issue by Bon-Y** [CMPUT301F22T01/FoodBit#20]
**Shopping List**

- Allow meal planners to add ingredients they have picked up to their ingredient storage, reminding them to complete details like location, actual amount

**Comment by Bon-Y** [comment]
Need to discuss: overlap functionality with ingredient storage?

**Comment by richeek05** [comment]
Fixed: ID for ingredient in the recipe to match the ID in ingredientList.
Fixed: Any overlap with ingredientList
