### ISSUE TITLE
US 00.04.00 (Add a Top Action Bar)

### ISSUE THREAD

**Issue by hobielee42** [CMPUT301F22T01/FoodBit#24]

**Comment by richeek05** [comment]
Top Action Bar 

> Changes the name based on the fragment.
> Changes the functionality based on the selected fragment.
> Adds a MealPlan/Ingredient/Recipe based on the Fragment the add option is being called on.
> Sorts the IngredientStorage/RecipeBook based on the Fragment the sorting option is being called on.

**Comment by richeek05** [comment]
Sorting Completed with all the options
