### ISSUE TITLE
US 01.06.01 (sorting ingredients)

### ISSUE THREAD

**Issue by hr-jackson** [CMPUT301F22T01/FoodBit#7]
US 01.06.01 - As a meal planner, I want to sort the list of ingredients by description, best before date, location, and ingredient category.

Expected Behaviour:
- There is a box in the top right hand corner that can be clicked
- Once clicked this will open a menu where the user can choose how they want their list to be sorted
- choices are sort by description, best before date, location, and category
- once a user clicks on one of the choices a new screen will pop up where than can choose to sort by A-Z (low to high) or Z-A (high to low)
- once user clicks the second sorting option, the sorted list will be displayed

**Comment by richeek05** [comment]
After choosing the sorting option, the user needs to choose to sort ascendingly or descendingly. Pop up implementation changed to menu item implementation.
