### ISSUE TITLE
US 02.02.01 Add Ingredient to Recipe

### ISSUE THREAD

**Issue by hobielee42** [CMPUT301F22T01/FoodBit#9]
Original user story:
As a meal planner, I want to add an ingredient to a recipe, with a brief description, amount, unit, and ingredient category.
Expected Behavior:
- [x] In the `view/edit recipe screen`, when the `add button` above the `ingredient list` is clicked, a dialog will pop up prompting the user to enter the following information:
**Mandatory**: description, amount unit;
**Optional**: ingredient category.
- [x] When the `done button` is clicked, the ingredient should be added as a candidate ingredient add will be added to the recipe in the database when the user finishes editing the recipe.
- [x] When the `back button` is clicked, the addition is aborted.

**Comment by hobielee42** [comment]
What is "unit" though?

**Comment by richeek05** [comment]
Ingredients in the Recipe are only added to the ingredientList once the Recipe is confirmed by the User, In case of editing the Recipe as well.
