### ISSUE TITLE
Finalize/Refine CRC Cards

### ISSUE THREAD

**Issue by richeek05** [CMPUT301F22T01/FoodBit#92]
- Refine the CRC Cards
- Make sure they follow the object-oriented design
- Cohesive Classes and Coupling management
- Keep updating CRC Cards

CRC CARDS:

![Image](https://user-images.githubusercontent.com/114626504/200055610-7083ec2b-2c20-4187-bc20-6cb75df4e531.png)

![Image](https://user-images.githubusercontent.com/114706858/195843232-bb6fcd04-66c5-490b-8948-00e523629b6c.png)

![Image](https://user-images.githubusercontent.com/114706858/195843306-4ffbe4d3-2804-467d-9cae-8f3dec927123.png)

![Image](https://user-images.githubusercontent.com/114706858/195843374-c397bd84-bcf0-4110-92d7-15d46d964ff1.png)

![Image](https://user-images.githubusercontent.com/114706858/195843457-123a6723-15ae-4dcc-98a8-967272665d2c.png)

![Image](https://user-images.githubusercontent.com/114706858/195843506-797f152b-58fb-466c-9751-fcfc029f0a11.png)

**Comment by richeek05** [comment]
Update the CRC Cards:
Feedback on Project Part 2 from TA: "here is a comment for CRC card for project part II. You did not lose any marks, but something to consider when creating the UML. A class for database connection should be added for the separation of concern"

To Do:
Add CRC Card for Database

**Comment by richeek05** [comment]
**Updated CRC Cards (Including DataBaseController CRC Card):**


IngredientStorage:
 >![Image](https://user-images.githubusercontent.com/114706858/200043389-5f5c6e4c-11c1-4e62-80a3-f674d4793296.png)
 >**Json Code:**
[
  {
    "name": "IngredientStorage",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keep track of ingredients",
      "Edit already existing ingredients",
      "Delete already existing ingredients",
      "Sort list of ingredients "
    ],
    "collaborators": [
      "Ingredient",
      "Recipe",
      "MealPlan ",
      "ShoppingList",
      "DatabaseController",
      ""
    ]
  }
]

RecipeBook:
 > ![Image](https://user-images.githubusercontent.com/114706858/200041986-1b230588-c02e-4683-ad3c-948ca8eb95b1.png)
 >**Json Code:**
[
  {
    "name": "RecipeBook",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keeps track of all the Recipes",
      "Edit existing Recipes(including Ingredients)",
      "Delete existing Recipes",
      "Sort the list of Recipes(by title, preparation time, number of servings, or recipe category)"
    ],
    "collaborators": [
      "Recipe",
      "MealPlan",
      "DatabaseController"
    ]
  }
]




MealPlanController:
 > ![Image](https://user-images.githubusercontent.com/114706858/200041183-259e2823-1eb3-4ed1-ad4b-d5d18cea293e.png)
 >**Json Code:**
 [
  {
    "name": "MealPlanController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Record information about recipes/ingredients, serving amounts, and the dates the recipes/ingredients are planned for",
      "Provide function to display information about current meal plan",
      "Add recipes/ingredients,serving amounts, and associated date",
      "Remove recipes/ingredients,serving amounts, and associated date",
      "Provide a function to calculate the total ingredients required for the mealplan by using the function from Recipe and taking into account serving size."
    ],
    "collaborators": [
      "Recipe",
      "Ingredient",
      "ShoppingList",
      "DatabaseController"
    ]
  }
]

DatabaseController:
 >![Image](https://user-images.githubusercontent.com/114706858/200043646-efd7d9a6-3a45-41be-9b72-8b17a55b7a9b.png)
 >**Json Code:**
[
  {
    "name": "DatabaseController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Get Firebase Instance ID",
      "Making a Collection",
      "Adding an Item",
      "Editing an Item",
      "Deleting an Item"
    ],
    "collaborators": [
      "IngredientStorage",
      "RecipeBook",
      "MealPlanController",
      "MainActivity",
      "LoadingPageActivity"
    ]
  }
]

**Comment by a-s-ahmed** [comment]
@richeek05  MealPlan only interacts with MealPlanController right?

**Comment by a-s-ahmed** [comment]
@richeek05 I've added an uodated MealPlan crc card to the wiki. Please update the MealPlanController with: 
"collaborators": [
"RecipeBook",
"IngredientStorage",
"ShoppingList",
"DatabaseController"
]

before posting the updated version to the wiki

**Comment by richeek05** [comment]
**Shopping Cart:**
  >![Image](https://user-images.githubusercontent.com/114706858/200071693-a73508ec-256f-4682-beac-21dea7b082d5.png)
  >![Image](https://user-images.githubusercontent.com/114706858/200071756-96e90199-d197-45fd-9984-ca23e39b897c.png)
  > **Json Code:**
[
  {
    "name": "ShoppingCartFragment",
    "superclasses": "FoodBit",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "List shopping waitlist of ingredients",
      "Show description of ingredients with amount, unit and category",
      "Sort shopping list by description or category",
      "Show the shopping list amount change(empty or not)",
      "Remind meal planner to complete ingredients details(location, actual amount and unit)",
      "",
      ""
    ],
    "collaborators": [
      "ShoppingCartAdapter",
      "IngredientStorage",
      "MealPlanController"
    ]
  },
  {
    "name": "ShoppingCardAdapter",
    "superclasses": "Foodbit",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "{ add it into shopping list } { reminded user finish actual amount}",
      "if the meal plan includes ingredients which not in storage of the ingredients",
      "if the meal plan includes ingredients in the storage of the ingredients but not enough",
      ""
    ],
    "collaborators": [
      "ShoppingCartFragment",
      "Ingredient",
      "IngredientStorage",
      "MealPlanController"
    ]
  }
]

**Comment by richeek05** [comment]
Ingredient:

![Image](https://user-images.githubusercontent.com/114626504/200075150-b30dd5e7-0a4c-4549-8ce7-090ee9fc11aa.png)

[
  {
    "name": "Ingredient",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "- keeps track of ingredient description",
      "- keeps track of ingredient best before date",
      "- keeps track of ingredient location",
      "- keeps track of ingredient amount",
      "- keeps track of ingredient unit",
      "- keeps track of ingredient category"
    ],
    "collaborators": [
      "IngredientStorage",
      "MealPlan ",
      "Recipe",
      "ShoppingList",
      "DatabaseController"
    ]
  }
]
    

IngredientStorage:


![Image](https://user-images.githubusercontent.com/114626504/200075399-5c080184-a1f3-42ff-993b-606f788b1e77.png)


[
  {
    "name": "IngredientStorage",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keep track of ingredients",
      "Edit already existing ingredients",
      "Delete already existing ingredients",
      "Sort list of ingredients ",
      "Add new ingredients"
    ],
    "collaborators": [
      "ShoppingList",
      "DatabaseController",
      ""
    ]
  }
]

![Image](https://user-images.githubusercontent.com/114626504/204173723-9ea54cc7-1704-49c1-8fa8-9eb1bf6054e8.png)

[
  {
    "name": "IngredientUnit",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keeps track of different units ingredients can have that are in the database",
      "Units can have a name and an id"
    ],
    "collaborators": [
      "IngredientUnitController"
    ]
  }
]


![Image](https://user-images.githubusercontent.com/114626504/204173685-48d18b3c-2d8f-4a12-aa38-fbc1371f7832.png)

[
  {
    "name": "IngredientCategory",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keep track of different categories ingredients can have that are in the database",
      "Categories can have a name and an id"
    ],
    "collaborators": [
      "IngredientCategoryController"
    ]
  }
]

![Image](https://user-images.githubusercontent.com/114626504/204173904-da2c04b2-9e2d-4b6a-9b4c-fd6ee6fc9885.png)

]
  {
    "name": "IngredientLocation",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keeps track of different locations that ingredients can have and are in the database",
      "Locations can have a name and an id"
    ],
    "collaborators": [
      "IngredientLocationController"
    ]
  }
]

![Image](https://user-images.githubusercontent.com/114626504/204174322-6e9f78f7-ee2e-4fff-9cd0-ab408fbdde81.png)

[
  {
    "name": "IngredientCategoryController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Add new category to database",
      "Remove existing category from database",
      "Load categories from database"
    ],
    "collaborators": [
      "IngredientCategory",
      "DatabaseController"
    ]
  }
]

![Image](https://user-images.githubusercontent.com/114626504/204174446-2c280c28-ff39-4278-9619-565d589c3627.png)

[
  {
    "name": "IngredientUnitController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Add new unit to database",
      "Remove existing unit from database",
      "Load units from database"
    ],
    "collaborators": [
      "IngredientUnit",
      "DatabaseController"
    ]
  }
]

![Image](https://user-images.githubusercontent.com/114626504/204174538-391b8a46-9de5-44ce-9ad1-8ec3071ebed6.png)

[
  {
    "name": "IngredientLocationController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Add new location to database",
      "Remove existing location from database",
      "Load location from database"
    ],
    "collaborators": [
      "IngredientLocation",
      "DatabaseController"
    ]
  }
]





![Image](https://user-images.githubusercontent.com/114706858/204393640-dc0c68ea-d724-43cb-920b-d0ca51b1cdca.png)

[
  {
    "name": "RecipeController",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Keep track of all the Recipes",
      "Add a new recipe",
      "Edit existing recipes (including ingredients)",
      "Delete existing recipes",
      "Sort the list of recipes (by title, preparation time, number of servings, or recipe category)"
    ],
    "collaborators": [
      "Recipe",
      "MealPlanController",
      "DatabaseController"
    ]
  }]



![Image](https://user-images.githubusercontent.com/114706858/204393696-13015c43-073a-4b40-a303-b4353b86bfb2.png)

[
  {
    "name": "Recipe",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Record information about a recipe including its title, preparation time, number of servings, recipe category, comments, photograph, and list of ingredients",
      "Add ingredients with a brief description, amount, unit, and ingredient category",
      "Delete an ingredient from the recipe",
      "Check if the entries are valid",
      "Provide a list of needed ingredients"
    ],
    "collaborators": [
      "RecipeController",
      "Ingredient"
    ]
  }
]

**Comment by richeek05** [comment]
![Image](https://user-images.githubusercontent.com/114706858/204394347-9c5792c4-6b4a-4f14-93f3-c26a82e3c391.png)

[
  {
    "name": "ShoppingCartFragment",
    "superclasses": "FoodBit",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "List shopping waitlist of ingredients",
      "Show description of ingredients with amount, unit and category",
      "Sort shopping list by description or category",
      "Show the shopping list amount change(empty or not)",
      "Remind meal planner to complete ingredients details(location, actual amount and unit)",
      "",
      ""
    ],
    "collaborators": [
      "ShoppingCartAdapter",
      "IngredientController",
      "Meal plan"
    ]
  }]



![Image](https://user-images.githubusercontent.com/114706858/204394393-d7a44621-28ae-4d5b-8950-b38924555ef6.png)



[  {
    "name": "ShoppingCardAdapter",
    "superclasses": "Foodbit",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "{ add it into shopping list } { reminded user finish actual amount}",
      "if the meal plan includes ingredients which not in storage of the ingredients",
      "if the meal plan includes ingredients in the storage of the ingredients but not enough",
      ""
    ],
    "collaborators": [
      "ShoppingCartFragment",
      "Ingredient",
      "IngredientController",
      "MealplanController"
    ]
  }]




![Image](https://user-images.githubusercontent.com/114706858/204394483-921b7e36-faf6-45d5-abd7-2867f9190417.png)


[
  {
    "name": "ShoppingCartPickedItemFragment",
    "superclasses": "",
    "subclasses": "",
    "type": 1,
    "responsibilities": [
      "Add picked ingredient's amount to ingredient storage"
    ],
    "collaborators": [
      "ShoppingCartFragment",
      "Ingredient",
      "IngredientController"
    ]
  }
]
